/**
 * Auto-generated by Midnight Compact Compiler for GhostFree.compact
 * Target: Midnight Network
 */

export interface Witnesses<T = unknown> {
  readonly residentID?: (context: T) => Uint8Array | Promise<Uint8Array>;
  readonly residentSecret?: (context: T) => Uint8Array | Promise<Uint8Array>;
  readonly merkleProof?: (context: T) => Uint8Array[] | Promise<Uint8Array[]>;
  readonly merkleDirections?: (context: T) => boolean[] | Promise<boolean[]>;
}

export interface Ledger {
  readonly merkleRoot: Uint8Array;
  readonly fundBalance: bigint;
  readonly perClaimAmount: bigint;
  readonly operationName: Uint8Array;
  readonly adminAddress: Uint8Array;
  readonly claimCount: bigint;
  readonly spentNullifiers: ReadonlyMap<Uint8Array, boolean>;
}

export interface Contract<T = unknown> {
  readonly witnesses: Witnesses<T>;
  readonly circuits: {
    readonly initialize: (
      context: T,
      root: Uint8Array,
      claimAmount: bigint,
      name: Uint8Array
    ) => Promise<void>;
    readonly claimAid: (
      context: T,
      residentID: Uint8Array,
      residentSecret: Uint8Array,
      merkleProof: Uint8Array[],
      merkleDirections: boolean[],
      nullifier: Uint8Array
    ) => Promise<void>;
    readonly withdrawRemaining: (context: T) => Promise<void>;
    readonly getStatus: (context: T) => Promise<[bigint, bigint, bigint]>;
  };
}

export declare const Contract: {
  new <T = unknown>(witnesses: Witnesses<T>): Contract<T>;
};

export declare const ledger: (state: unknown) => Ledger;
