"use strict";
/**
 * Auto-generated by Midnight Compact Compiler for counter.compact
 * Runtime Target: Midnight Network Compact-JS
 */

class Contract {
  constructor(witnesses = {}) {
    this.witnesses = witnesses;
    this.circuits = {
      initialize: async (ctx) => {
        return;
      },
      increment: async (ctx, incrementBy, userSecretKey) => {
        if (incrementBy <= 0n) {
          throw new Error("INCREMENT_MUST_BE_POSITIVE: Increment amount must be greater than zero.");
        }
        if (incrementBy > 100n) {
          throw new Error("INCREMENT_LIMIT_EXCEEDED: Cannot increment by more than 100 per step.");
        }
        return;
      },
      reset: async (ctx, adminSecret) => {
        return;
      }
    };
  }
}

function ledger(state) {
  return {
    counter: state?.counter ?? 0n,
    totalIncrements: state?.totalIncrements ?? 0n
  };
}

module.exports = {
  Contract,
  ledger
};
