/**
 * Auto-generated by Midnight Compact Compiler for counter.compact
 * Target: Midnight Network
 */

export interface Witnesses<T = unknown> {
  readonly incrementBy?: (context: T) => bigint | Promise<bigint>;
  readonly userSecretKey?: (context: T) => Uint8Array | Promise<Uint8Array>;
  readonly adminSecret?: (context: T) => Uint8Array | Promise<Uint8Array>;
}

export interface Ledger {
  readonly counter: bigint;
  readonly totalIncrements: bigint;
}

export interface Contract<T = unknown> {
  readonly witnesses: Witnesses<T>;
  readonly circuits: {
    readonly initialize: (context: T) => Promise<void>;
    readonly increment: (context: T, incrementBy: bigint, userSecretKey: Uint8Array) => Promise<void>;
    readonly reset: (context: T, adminSecret: Uint8Array) => Promise<void>;
  };
}

export declare const Contract: {
  new <T = unknown>(witnesses: Witnesses<T>): Contract<T>;
};

export declare const ledger: (state: unknown) => Ledger;
